# The ID of the ArUco marker whose position is to be retrieved.
int32 aruco_id

---
# Indicates whether the request was successful (true) or not (false).
# Will be 'false' if the requested ID is not present in the context.
bool success

# The 2D position of the marker.
# Using geometry_msgs/Point for convention, setting z = 0.
geometry_msgs/Point position
# A text message that can contain additional information.
string message
