# GetCookie.srv
# Service called by Mangiafuoco to request CookieTrader 
# to communicate task completion to the Mission Manager and get points.

# =========================== REQUEST ===========================
# This is the data that Mangiafuoco sends to CookieTrader.

### Task info that Mangiafuoco already has ###
int32 task_id
string task_type
string request_time

# Leave empty if not needed for the specific task
int32[] target_ids 
string object_name

### Results ###
string completion_time
sensor_msgs/CompressedImage[] photo_list
string success_message # Internal success message from the puppet

---

# =========================== RESPONSE ============================
# This is the data that CookieTrader returns to Mangiafuoco 
# after communicating with the MM.

# Flag to indicate if communication with the MM was successful
bool mm_accepted 

# Response message from MM or internal status from CookieTrader
# e.g.: "OK", "Points registered", "Error: MM timeout", etc.
string mm_response